package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCPayOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAllPropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertHCPayOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertHCPayOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAllUpdatablePropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertHCPayOptionUpdatableFieldsEquals(expected, actual);
        assertHCPayOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAutoGeneratedPropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertThat(expected)
            .as("Verify HCPayOption auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionUpdatableFieldsEquals(HCPayOption expected, HCPayOption actual) {
        assertThat(expected)
            .as("Verify HCPayOption relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getUserID()).as("check userID").isEqualTo(actual.getUserID()))
            .satisfies(e -> assertThat(e.getMetadata()).as("check metadata").isEqualTo(actual.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionUpdatableRelationshipsEquals(HCPayOption expected, HCPayOption actual) {}
}
