package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAllPropertiesEquals(IDocument expected, IDocument actual) {
        assertHCDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertHCDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAllUpdatablePropertiesEquals(IDocument expected, IDocument actual) {
        assertHCDocumentUpdatableFieldsEquals(expected, actual);
        assertHCDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAutoGeneratedPropertiesEquals(IDocument expected, IDocument actual) {
        assertThat(expected)
            .as("Verify HCDocument auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentUpdatableFieldsEquals(IDocument expected, IDocument actual) {
        assertThat(expected)
            .as("Verify HCDocument relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getProfileId()).as("check profileId").isEqualTo(actual.getProfileId()))
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()))
            .satisfies(e -> assertThat(e.getDataContentType()).as("check data contenty type").isEqualTo(actual.getDataContentType()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getModifiedDate()).as("check modifiedDate").isEqualTo(actual.getModifiedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentUpdatableRelationshipsEquals(IDocument expected, IDocument actual) {}
}
