package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetadataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAllPropertiesEquals(Metadata expected, Metadata actual) {
        assertMetadataAutoGeneratedPropertiesEquals(expected, actual);
        assertMetadataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAllUpdatablePropertiesEquals(Metadata expected, Metadata actual) {
        assertMetadataUpdatableFieldsEquals(expected, actual);
        assertMetadataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAutoGeneratedPropertiesEquals(Metadata expected, Metadata actual) {
        assertThat(expected)
            .as("Verify Metadata auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataUpdatableFieldsEquals(Metadata expected, Metadata actual) {
        assertThat(expected)
            .as("Verify Metadata relevant properties")
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getModifiedBy()).as("check modifiedBy").isEqualTo(actual.getModifiedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getModifiedDate()).as("check modifiedDate").isEqualTo(actual.getModifiedDate()))
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataUpdatableRelationshipsEquals(Metadata expected, Metadata actual) {}
}
