package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonalDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalDocumentAllPropertiesEquals(PersonalDocument expected, PersonalDocument actual) {
        assertPersonalDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonalDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalDocumentAllUpdatablePropertiesEquals(PersonalDocument expected, PersonalDocument actual) {
        assertPersonalDocumentUpdatableFieldsEquals(expected, actual);
        assertPersonalDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalDocumentAutoGeneratedPropertiesEquals(PersonalDocument expected, PersonalDocument actual) {
        assertThat(expected)
            .as("Verify PersonalDocument auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalDocumentUpdatableFieldsEquals(PersonalDocument expected, PersonalDocument actual) {
        assertThat(expected)
            .as("Verify PersonalDocument relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getProfileId()).as("check profileId").isEqualTo(actual.getProfileId()))
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()))
            .satisfies(e -> assertThat(e.getDataContentType()).as("check data contenty type").isEqualTo(actual.getDataContentType()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getModifiedDate()).as("check modifiedDate").isEqualTo(actual.getModifiedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalDocumentUpdatableRelationshipsEquals(PersonalDocument expected, PersonalDocument actual) {}
}
