package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RosterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAllPropertiesEquals(Roster expected, Roster actual) {
        assertRosterAutoGeneratedPropertiesEquals(expected, actual);
        assertRosterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAllUpdatablePropertiesEquals(Roster expected, Roster actual) {
        assertRosterUpdatableFieldsEquals(expected, actual);
        assertRosterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAutoGeneratedPropertiesEquals(Roster expected, Roster actual) {
        assertThat(expected)
            .as("Verify Roster auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterUpdatableFieldsEquals(Roster expected, Roster actual) {
        assertThat(expected)
            .as("Verify Roster relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getProfessionalId()).as("check professionalId").isEqualTo(actual.getProfessionalId()))
            .satisfies(e -> assertThat(e.getSchedule()).as("check schedule").isEqualTo(actual.getSchedule()))
            .satisfies(e -> assertThat(e.getDuration()).as("check duration").isEqualTo(actual.getDuration()))
            .satisfies(e -> assertThat(e.getTasks()).as("check tasks").isEqualTo(actual.getTasks()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getModifiedDate()).as("check modifiedDate").isEqualTo(actual.getModifiedDate()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getModifiedBy()).as("check modifiedBy").isEqualTo(actual.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterUpdatableRelationshipsEquals(Roster expected, Roster actual) {}
}
